apiVersion: v1
kind: Service
metadata:
  name: node-hello
spec:
  type: NodePort
  ports:
    - nodePort: {{ .Values.service.nodePort }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: node-hello
